# Generated by Django 3.1.2 on 2021-11-01 18:18

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('DorP', models.CharField(default='1', max_length=2)),
                ('line1', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('pincode', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=500)),
                ('cpassword', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('summary', models.TextField(max_length=1000)),
                ('content', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
