# Generated by Django 3.1.2 on 2021-10-28 12:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('line1', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('pincode', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=500)),
                ('cpassword', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
