# Generated by Django 3.1.2 on 2021-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211028_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DorP',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
