# Generated by Django 3.1.2 on 2021-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_dorp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DorP',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
